# Generated by Django 3.1.5 on 2021-01-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bill',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='billdetails',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='company',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='companyaccount',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='companybank',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customerrequest',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='employeebank',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='employeesalary',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='medicaldetails',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='medicine',
            managers=[
            ],
        ),
    ]
